[theme]
base="dark"
primaryColor="#c98bdb"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[deprecation]
showPyplotGlobalUse = false
showWarningOnDirectExecution = false